<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="any_axis_arm">

	<ros2_control name="FakeSystem" type="system">

		<hardware>
			<plugin>fake_components/GenericSystem</plugin>
		</hardware>

		<joint name="m_joint_1">
			<command_interface name="position">
				<param name="min"> -2.3562</param>
				<param name="max"> 2.3562</param>
			</command_interface>
			<state_interface name="position"/>
			<state_interface name="velocity"/>
		</joint>

		<joint name="m_joint_2">
			<command_interface name="position">
				<param name="min"> -2.3562</param>
				<param name="max"> 2.3562</param>
			</command_interface>
			<state_interface name="position"/>
			<state_interface name="velocity"/>
		</joint>

		<joint name="m_joint_3">
			<command_interface name="position">
				<param name="min"> -2.3562</param>
				<param name="max"> 2.3562</param>
			</command_interface>
			<state_interface name="position"/>
			<state_interface name="velocity"/>
		</joint>

		<joint name="m_joint_4">
			<command_interface name="position">
				<param name="min"> -2.3562</param>
				<param name="max"> 2.3562</param>
			</command_interface>
			<state_interface name="position"/>
			<state_interface name="velocity"/>
		</joint>
		<joint name="s_joint_z">
			<command_interface name="position">
				<param name="min"> 0.05</param>
				<param name="max"> 0.45</param>
			</command_interface>
			<state_interface name="position"/>
			<state_interface name="velocity"/>
		</joint>
		<joint name="s_joint_1">
			<command_interface name="position">
				<param name="min"> -2.3562</param>
				<param name="max"> 2.3562</param>
			</command_interface>
			<state_interface name="position"/>
			<state_interface name="velocity"/>
		</joint>
		<joint name="s_joint_2">
			<command_interface name="position">
				<param name="min"> -2.3562</param>
				<param name="max"> 2.3562</param>
			</command_interface>
			<state_interface name="position"/>
			<state_interface name="velocity"/>
		</joint>
		<joint name="s_end_joint_y">
			<command_interface name="position">
				<param name="min"> -2.3562</param>
				<param name="max"> 2.3562</param>
			</command_interface>
			<state_interface name="position"/>
			<state_interface name="velocity"/>
		</joint>
		<joint name="s_end_joint_z">
			<command_interface name="position">
				<param name="min"> -2.3562</param>
				<param name="max"> 2.3562</param>
			</command_interface>
			<state_interface name="position"/>
			<state_interface name="velocity"/>
		</joint>
	</ros2_control>

	<gazebo>
		<plugin name="gazebo_ros2_control" filename="libgazebo_ros2_control.so">
			<parameters>$(find complete_robot)/config/controllers.yaml</parameters>
		</plugin>
	</gazebo>

	<xacro:property name="m_link_width" value="0.04"/>
	<xacro:property name="m_link1_length" value="0.2"/>
	<xacro:property name="m_link2_length" value="0.2"/>
	<xacro:property name="m_link3_length" value="0.05"/>
	<xacro:property name="end_effector_radius" value="0.04"/>




	<xacro:property name="s_link_z_length" value="0.5" />
	<xacro:property name="s_link1_length" value="0.2" />
	<xacro:property name="s_link2_length" value="0.2" />
	<xacro:property name="link_radius" value="0.02" />
	<material name="blue"><color rgba="0.1 0.1 0.8 1.0"/></material>
	<material name="green"><color rgba="0.1 0.8 0.1 1.0"/></material>
	<material name="grey"><color rgba="0.5 0.5 0.5 1.0"/></material>
	<material name="red"><color rgba="0.8 0.1 0.1 1.0"/></material>


<!-- ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ -->


	<link name="world" />

	<link name="m_base_link"><!--                 master base link 설정                -->
		<visual>
			<geometry>
				<cylinder radius="0.05" length="0.1"/>
			</geometry>
			<material name="grey"/>
		</visual>
        <collision>
        	<geometry>
        		<cylinder radius="0.05" length="0.1"/>
        	</geometry>
        </collision>
        <inertial>
        	<mass value="1"/>
        	<inertia ixx="0.001" ixy="0" ixz="0"
        		iyy="0.001" iyz="0" izz="0.001"/>
        </inertial>
    </link>

    <joint name="world_to_m_base" type="fixed"><!--   world ro master base joint 설정  -->
    	<parent link="world"/>
    	<child link="m_base_link"/>
    	<origin xyz="0 0 0.05" rpy="0 0 0"/>
    </joint>

    <link name="m_link_1"><!--                   master link 1 설정                    -->
        <visual>
        	<origin xyz="${m_link1_length/2} 0 0"/>
        	<geometry>
        		<box size="${m_link1_length} ${m_link_width} 0.04"/>
        	</geometry>
        	<material name="blue"/>
        </visual>
        <collision>
        	<origin xyz="${m_link1_length/2} 0 0"/>
        	<geometry>
        		<box size="${m_link1_length} ${m_link_width} 0.04"/>
        	</geometry>
        </collision>
        <inertial>
        	<mass value="0.2"/>
        	<origin xyz="${m_link1_length/2} 0 0" rpy="0 0 0"/>
        	<inertia ixx="0.000054" ixy="0.0" ixz="0.0" 
        		iyy="0.000694" iyz="0.0" izz="0.000694"/>
        </inertial>
    </link>

    <joint name="m_joint_1" type="revolute"><!--         master jonit 1 설정          -->
        <parent link="m_base_link" />
        <child link="m_link_1" />
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <axis xyz="0 0 1"/>
        <limit lower="-2.3562" upper="2.3562" effort="1.5" velocity="6.38791"/>
    </joint>

    <link name="m_link_2"><!--                    master link 2 설정                  -->
        <visual>
        	<origin xyz="${m_link2_length/2} 0 0"/>
        	<geometry>
        		<box size="${m_link2_length} ${m_link_width} 0.04"/>
        	</geometry>
        	<material name="green"/>
        </visual>
        <collision>
        	<origin xyz="${m_link2_length/2} 0 0"/>
        	<geometry>
        		<box size="${m_link2_length} ${m_link_width} 0.04"/>
        	</geometry>
        </collision>
        <inertial>
        	<mass value="0.2"/>
        	<origin xyz="${m_link2_length/2} 0 0" rpy="0 0 0"/>
        	<inertia ixx="0.000054" ixy="0.0" ixz="0.0" 
        		iyy="0.000694" iyz="0.0" izz="0.000694"/>
        </inertial>
    </link>
    
    <joint name="m_joint_2" type="revolute">
        <parent link="m_link_1" />
        <child link="m_link_2" />
        <origin xyz="${m_link1_length} 0 0" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
        <limit lower="-2.3562" upper="2.3562" effort="1.5" velocity="6.38791"/>
    </joint>

	<link name="m_link_3">
		<visual>
			<origin xyz="${m_link3_length/2} 0 0"/>
			<geometry>
				<box size="${m_link3_length} ${m_link_width} 0.04"/>
			</geometry>
			<material name="green"/>
		</visual>
		<collision>
			<origin xyz="${m_link3_length/2} 0 0"/>
			<geometry>
				<box size="${m_link3_length} ${m_link_width} 0.04"/>
			</geometry>
		</collision>
		<inertial>
			<mass value="0.1"/>
			<origin xyz="${m_link3_length/2} 0 0" rpy="0 0 0"/>
			<inertia ixx="0.0001" ixy="0.0" ixz="0.0" 
				iyy="0.0001" iyz="0.0" izz="0.0001"/>
		</inertial>
	</link>

	<joint name="m_joint_3" type="revolute">
		<parent link="m_link_2" />
		<child link="m_link_3" />
		<origin xyz="${m_link2_length} 0 0" rpy="0 0 0"/>
		<axis xyz="0 1 0"/>
		<limit lower="-2.3562" upper="2.3562" effort="1.5" velocity="6.38791"/>
	</joint>

	<link name="m_end_effector">
		<visual>
			<origin xyz="${end_effector_radius} 0 0" />
			<geometry>
				<sphere radius="${end_effector_radius}" />
			</geometry>
			<material name="red"/>
		</visual>
		<collision>
			<origin xyz="${end_effector_radius} 0 0" rpy="0 0 0" />
			<geometry>
				<sphere radius="${end_effector_radius}" />
			</geometry>
		</collision>
		<inertial>
			<mass value="0.01" />
			<origin xyz="0 0 0" rpy="0 0 0" />
			<inertia ixx="0.0001" ixy="0" ixz="0" 
				iyy="0.0001" iyz="0" izz="0.0001" />
		</inertial>
	</link>

	<joint name="m_joint_4" type="revolute">
		<parent link="m_link_3" />
		<child link="m_end_effector" />
		<origin xyz="${m_link3_length} 0 0" rpy="0 0 0" />
		<axis xyz="0 0 1" />
		<limit lower="-2.3562" upper="2.3562" effort="1.5" velocity="6.38791" />
	</joint>



<!-- ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ -->



	<link name="s_pole_link">
		<visual>
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<geometry>
				<cylinder radius="0.025" length="${s_link_z_length}"/>
			</geometry>
			<material name="grey"/>
		</visual>
        <collision>
        	<origin xyz="0 0 0" rpy="0 0 0"/>
        	<geometry>
        		<cylinder radius="0.02" length="${s_link_z_length}"/>
        	</geometry>
        </collision>
        <inertial>
        	<mass value="1"/>
        	<inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
        </inertial>
    </link>

    <joint name="world_to_s_pole" type="fixed">
    	<parent link="world"/>
    	<child link="s_pole_link"/>
    	<origin xyz="0 0.5 0.25" rpy="0 0 0"/>
    </joint>

    <link name='s_slider_link'>
    	<visual>
    		<origin xyz="0 0 0" rpy="0 0 0"/>
    		<geometry>
    			<cylinder radius="0.1" length="0.04"/>
    		</geometry>
    		<material name="blue"/>
    	</visual>
    	<collision>
    		<origin xyz="0 0 0" rpy="0 0 0"/>
    		<geometry>
    			<cylinder radius="0.1" length="0.04"/>
    		</geometry>
    	</collision>
    	<inertial>
        	<mass value="1"/>
        	<inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
    	</inertial>
    </link>

    <joint name="s_joint_z" type="prismatic">
    	<parent link="s_pole_link"/>
    	<child link="s_slider_link"/>
    	<origin xyz="0 0 -0.15" rpy="0 0 0"/>
    	<axis xyz="0 0 1"/>
    	<limit lower="0.05" upper="0.45" effort="100" velocity="0.1"/>
    </joint>

    <link name="s_base_link">
    	<visual>
    		<origin xyz="0.1 0 -0.04"/>
    		<geometry>
    			<box size="0.2 0.04 0.04"/>
    		</geometry>
    		<material name="blue"/>
    	</visual>
        <collision>
        	<origin xyz="0.2 0 -0.04" rpy="0 0 0"/>
        	<geometry>
        		<box size="0.1 0.04 0.04"/>
        	</geometry>
        </collision>
        <inertial>
        	<mass value="0.1"/>
        	<inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
        </inertial>
    </link>

    <joint name="s_slider_to_base" type="fixed">
    	<parent link="s_slider_link"/>
    	<child link="s_base_link"/>
    	<origin xyz="0 0 0.04" rpy="0 0 0"/>
    </joint>

	<link name="s_link_1">
        <visual>
        	<origin xyz="${s_link1_length/2} 0 0"/>
        	<geometry>
        		<box size="${s_link1_length} 0.04 0.04"/>
        	</geometry>
        	<material name="blue"/>
        </visual>
        <collision>
        	<origin xyz="${s_link1_length/2} 0 0"/>
        	<geometry>
        		<box size="${s_link1_length} 0.04 0.04"/>
        	</geometry>
        </collision>
        <inertial>
        	<mass value="0.2"/>
        	<origin xyz="${s_link1_length/2} 0 0" rpy="0 0 0"/>
        	<inertia ixx="0.000054" ixy="0.0" ixz="0.0" iyy="0.000694" iyz="0.0" izz="0.000694"/>
        </inertial>
    </link>

    <joint name="s_joint_1" type="revolute">
        <parent link="s_base_link" />
        <child link="s_link_1" />
        <origin xyz="0.2 0 -0.04" rpy="0 0 0"/>
        <axis xyz="0 0 1"/>
        <limit lower="-2.3562" upper="2.3562" effort="1.5" velocity="6.38791"/>
    </joint>
 
<!--                 link_2 물리량 설정                  -->

    <link name="s_link_2">
        <visual>
        	<origin xyz="${s_link2_length/2} 0 0"/>
        	<geometry>
        		<box size="${s_link2_length} 0.04 0.04"/>
        	</geometry>
        	<material name="green"/>
        </visual>
        <collision>
        	<origin xyz="${s_link2_length/2} 0 0"/>
        	<geometry>
        		<box size="${s_link2_length} 0.04 0.04"/>
        	</geometry>
        </collision>
        <inertial>
        	<mass value="0.2"/>
        	<origin xyz="${s_link2_length/2} 0 0" rpy="0 0 0"/>
        	<inertia ixx="0.000054" ixy="0.0" ixz="0.0" iyy="0.000694" iyz="0.0" izz="0.000694"/>
        </inertial>
    </link>
    
    <joint name="s_joint_2" type="revolute">
        <parent link="s_link_1" />
        <child link="s_link_2" />
        <origin xyz="${s_link1_length} 0 0" rpy="0 0 0"/>
        <axis xyz="0 0 1"/>
        <limit lower="-2.3562" upper="2.3562" effort="1.5" velocity="6.38791"/>
    </joint>
</robot>



