<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="any_axis_arm">

	<xacro:property name="PI" value="3.141592653589793"/>
	<xacro:property name="degree_100" value="${100 * PI / 180}"/>
	<xacro:property name="degree_135" value="${135 * PI / 180}" />
	<xacro:property name="slave_z_minimum" value="0.05"/>
	<xacro:property name="slave_z_maximum" value="0.45"/>
	<xacro:property name="m_link_width" value="0.04"/>
	<xacro:property name="m_link1_length" value="0.17"/>
	<xacro:property name="m_link2_length" value="0.155"/>
	<xacro:property name="m_link3_length" value="0.05"/>
	<xacro:property name="end_effector_radius" value="0.04"/>
	<xacro:property name="s_link_z_length" value="0.5" />
	<xacro:property name="s_link1_length" value="0.2" />
	<xacro:property name="s_link2_length" value="0.2" />
	<xacro:property name="s_end_effector_length" value="0.05" />
	<xacro:property name="s_suction_cup_length" value="0.02"/>
	<xacro:property name="link_radius" value="0.02" />
	<xacro:property name="suction_cup_radius" value="0.05" />

	<material name="blue"><color rgba="0.1 0.1 0.8 1.0"/></material>
	<material name="green"><color rgba="0.1 0.8 0.1 1.0"/></material>
	<material name="grey"><color rgba="0.5 0.5 0.5 1.0"/></material>
	<material name="red"><color rgba="0.8 0.1 0.1 1.0"/></material>

	<ros2_control name="FakeSystem" type="system">
		<hardware>
			<plugin>fake_components/GenericSystem</plugin>
		</hardware>

		<joint name="m_joint_1">
			<command_interface name="position">
				<param name="min"> ${- degree_100}</param>
				<param name="max"> ${degree_100}</param>
			</command_interface>
			<state_interface name="position"/>
			<state_interface name="velocity"/>
		</joint>

		<joint name="m_joint_2">
			<command_interface name="position">
				<param name="min"> ${- degree_100}</param>
				<param name="max"> ${degree_100}</param>
			</command_interface>
			<state_interface name="position"/>
			<state_interface name="velocity"/>
		</joint>

		<joint name="m_joint_3">
			<command_interface name="position">
				<param name="min"> ${- degree_100}</param>
				<param name="max"> ${degree_100}</param>
			</command_interface>
			<state_interface name="position"/>
			<state_interface name="velocity"/>
		</joint>

		<joint name="m_joint_4">
			<command_interface name="position">
				<param name="min"> ${- degree_100}</param>
				<param name="max"> ${degree_100}</param>
			</command_interface>
			<state_interface name="position"/>
			<state_interface name="velocity"/>
		</joint>
		<joint name="s_joint_z">
			<command_interface name="position">
				<param name="min"> ${slave_z_minimum}</param>
				<param name="max"> ${slave_z_maximum}</param>
			</command_interface>
			<state_interface name="position"/>
			<state_interface name="velocity"/>
		</joint>
		<joint name="s_joint_1">
			<command_interface name="position">
				<param name="min"> ${- degree_135}</param>
				<param name="max"> ${degree_135}</param>
			</command_interface>
			<state_interface name="position"/>
			<state_interface name="velocity"/>
		</joint>
		<joint name="s_joint_2">
			<command_interface name="position">
				<param name="min"> ${- degree_135}</param>
				<param name="max"> ${degree_135}</param>
			</command_interface>
			<state_interface name="position"/>
			<state_interface name="velocity"/>
		</joint>
		<joint name="s_end_joint_y">
			<command_interface name="position">
				<param name="min"> ${- degree_135}</param>
				<param name="max"> ${degree_135}</param>
			</command_interface>
			<state_interface name="position"/>
			<state_interface name="velocity"/>
		</joint>
		<joint name="s_end_joint_z">
			<command_interface name="position">
				<param name="min"> ${- degree_135}</param>
				<param name="max"> ${degree_135}</param>
			</command_interface>
			<state_interface name="position"/>
			<state_interface name="velocity"/>
		</joint>
	</ros2_control>

	<gazebo>
		<plugin name="fake_components" filename="libgazebo_ros2_control.so">
			<parameters>$(find complete_robot)/config/controllers.yaml</parameters>
		</plugin>
	</gazebo>

	


<!-- ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ -->


	<link name="world" />

	<link name="base_link"><!--                 master base link 설정                -->
		<visual>
			<geometry>
				<cylinder radius="0.05" length="0.1"/>
			</geometry>
			<material name="grey"/>
		</visual>
        <collision>
        	<geometry>
        		<cylinder radius="0.05" length="0.1"/>
        	</geometry>
        </collision>
        <inertial>
        	<mass value="1"/>
        	<inertia ixx="0.001" ixy="0" ixz="0"
        		iyy="0.001" iyz="0" izz="0.001"/>
        </inertial>
    </link>

    <joint name="world_to_m_base" type="fixed"><!--   world ro master base joint 설정  -->
    	<parent link="world"/>
    	<child link="base_link"/>
    	<origin xyz="0 0 0.05" rpy="0 0 0"/>
    </joint>

    <link name="m_link_1"><!--                   master link 1 설정                    -->
        <visual>
        	<origin xyz="${m_link1_length/2} 0 0"/>
        	<geometry>
        		<box size="${m_link1_length} ${m_link_width} 0.04"/>
        	</geometry>
        	<material name="blue"/>
        </visual>
        <collision>
        	<origin xyz="${m_link1_length/2} 0 0"/>
        	<geometry>
        		<box size="${m_link1_length} ${m_link_width} 0.04"/>
        	</geometry>
        </collision>
        <inertial>
        	<mass value="0.2"/>
        	<origin xyz="${m_link1_length/2} 0 0" rpy="0 0 0"/>
        	<inertia ixx="0.000054" ixy="0.0" ixz="0.0" 
        		iyy="0.000694" iyz="0.0" izz="0.000694"/>
        </inertial>
    </link>

    <joint name="m_joint_1" type="revolute"><!--         master jonit 1 설정          -->
        <parent link="base_link" />
        <child link="m_link_1" />
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <axis xyz="0 0 1"/>
        <limit lower="${-degree_100}" upper="${degree_100}" effort="1.5" velocity="6.38791"/>
    </joint>

	<link name="m_link_2">
		<visual>
			<origin xyz="${m_link2_length/2} 0 0"/>
			<geometry>
				<box size="${m_link2_length} ${m_link_width} 0.04"/>
			</geometry>
			<material name="green"/>
		</visual>
		<collision>
			<origin xyz="${m_link2_length/2} 0 0"/>
			<geometry>
				<box size="${m_link2_length} ${m_link_width} 0.04"/>
			</geometry>
		</collision>
		<inertial>
			<mass value="0.2"/>
			<origin xyz="${m_link2_length/2} 0 0" rpy="0 0 0"/>
			<inertia ixx="0.000054" ixy="0.0" ixz="0.0" iyy="0.000694" iyz="0.0" izz="0.000694"/>
		</inertial>
	</link>

	<joint name="m_joint_2" type="revolute">
		<parent link="m_link_1" />
		<child link="m_link_2" />
		<origin xyz="${m_link1_length} 0 0" rpy="0 0 0"/>
		<axis xyz="0 1 0"/>
		<limit lower="${-degree_100}" upper="${degree_100}" effort="1.5" velocity="6.38791"/>
	</joint>

<link name="m_link_3">
		<visual>
			<origin xyz="${m_link3_length/2} 0 0"/>
			<geometry>
				<box size="${m_link3_length} ${m_link_width} 0.04"/>
			</geometry>
			<material name="green"/>
		</visual>
		<collision>
			<origin xyz="${m_link3_length/2} 0 0"/>
			<geometry>
				<box size="${m_link3_length} ${m_link_width} 0.04"/>
			</geometry>
		</collision>
		<inertial>
			<mass value="0.1"/>
			<origin xyz="${m_link3_length/2} 0 0" rpy="0 0 0"/>
			<inertia ixx="0.0001" ixy="0.0" ixz="0.0" 
				iyy="0.0001" iyz="0.0" izz="0.0001"/>
		</inertial>
	</link>

	<joint name="m_joint_3" type="revolute">
		<parent link="m_link_2" />
		<child link="m_link_3" />
        <origin xyz="${m_link2_length} 0 0" rpy="0 0 0"/>
		<axis xyz="0 1 0"/>
		<limit lower="${-degree_100}" upper="${degree_100}" effort="1.5" velocity="6.38791"/>
	</joint>

<link name="m_end_effector">
	<visual>
		<origin xyz="${end_effector_radius} 0 0" />
		<geometry>
			<sphere radius="${end_effector_radius}" />
		</geometry>
		<material name="red"/>
	</visual>
	<collision>
		<origin xyz="${end_effector_radius} 0 0" rpy="0 0 0" />
		<geometry>
			<sphere radius="${end_effector_radius}" />
		</geometry>
	</collision>
	<inertial>
		<mass value="0.01" />
		<origin xyz="0 0 0" rpy="0 0 0" />
		<inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001" />
	</inertial>
</link>

<joint name="m_joint_4" type="revolute">
		<parent link="m_link_3" />
		<child link="m_end_effector" />
		<origin xyz="${m_link3_length} 0 0" rpy="0 0 0" />
		<axis xyz="0 0 1" />
		<limit lower="${-degree_100}" upper="${degree_100}" effort="1.5" velocity="6.38791"/>
	</joint>    



<!-- ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ -->



	<link name="s_pole_link">
		<visual>
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<geometry>
				<cylinder radius="0.025" length="${s_link_z_length}"/>
			</geometry>
			<material name="grey"/>
		</visual>
        <collision>
        	<origin xyz="0 0 0" rpy="0 0 0"/>
        	<geometry>
        		<cylinder radius="0.02" length="${s_link_z_length}"/>
        	</geometry>
        </collision>
        <inertial>
        	<mass value="1"/>
        	<inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
        </inertial>
    </link>

    <joint name="world_to_s_pole" type="fixed">
    	<parent link="world"/>
    	<child link="s_pole_link"/>
    	<origin xyz="0 0.5 0.25" rpy="0 0 0"/>
    </joint>

    <link name='s_slider_link'>
    	<visual>
    		<origin xyz="0 0 0" rpy="0 0 0"/>
    		<geometry>
    			<cylinder radius="0.1" length="0.04"/>
    		</geometry>
    		<material name="blue"/>
    	</visual>
    	<collision>
    		<origin xyz="0 0 0" rpy="0 0 0"/>
    		<geometry>
    			<cylinder radius="0.1" length="0.04"/>
    		</geometry>
    	</collision>
    	<inertial>
        	<mass value="1"/>
        	<inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
    	</inertial>
    </link>

    <joint name="s_joint_z" type="prismatic">
    	<parent link="s_pole_link"/>
    	<child link="s_slider_link"/>
    	<origin xyz="0 0 -0.15" rpy="0 0 0"/>
    	<axis xyz="0 0 1"/>
    	<limit lower="${slave_z_minimum}" upper="${slave_z_maximum}" effort="100" velocity="0.1"/>
    </joint>

    <link name="s_base_link">
    	<visual>
    		<origin xyz="0.09 0 0"/>
    		<geometry>
    			<box size="0.18 0.04 0.04"/>
    		</geometry>
    		<material name="blue"/>
    	</visual>
    	<visual> 
    		<origin xyz="0.18 0 0"/>
    		<geometry>
    			<cylinder radius="0.02" length="0.04"/>
    		</geometry>
    		<material name="blue"/>
    	</visual>
        <collision>
        	<origin xyz="0.14 0 0" rpy="0 0 0"/>
        	<geometry>
        		<box size="0.08 0.04 0.04"/>
        	</geometry>
        </collision>
        <collision> 
    		<origin xyz="0.18 0 0"/>
    		<geometry>
    			<cylinder radius="0.02" length="0.04"/>
    		</geometry>
    		<material name="blue"/>
    	</collision>
        <inertial>
        	<mass value="0.1"/>
        	<inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
        </inertial>
    </link>

    <joint name="s_slider_to_base" type="fixed">
    	<parent link="s_slider_link"/>
    	<child link="s_base_link"/>
    	<origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

	<link name="s_link_1">
        <visual>
        	<origin xyz="${s_link1_length/2} 0 0"/>
        	<geometry>
        		<box size="${s_link1_length} 0.04 0.04"/>
        	</geometry>
        	<material name="blue"/>
        </visual>
        <visual> <!-- 둥근 부분 -->
    		<origin xyz="0 0 0"/>
    		<geometry>
    			<cylinder radius="0.02" length="0.04"/>
    		</geometry>
    		<material name="blue"/>
    	</visual>
        <visual>
    		<origin xyz="${s_link1_length} 0 0"/>
    		<geometry>
    			<cylinder radius="0.02" length="0.04"/>
    		</geometry>
    		<material name="blue"/>
    	</visual>
        <collision>
        	<origin xyz="${s_link1_length/2} 0 0"/>
        	<geometry>
        		<box size="${s_link1_length} 0.04 0.04"/>
        	</geometry>
        </collision>
        <collision> <!-- 둥근 부분 -->
    		<origin xyz="0 0 0"/>
    		<geometry>
    			<cylinder radius="0.02" length="0.04"/>
    		</geometry>
    		<material name="blue"/>
    	</collision>
        <collision>
    		<origin xyz="${s_link1_length} 0 0"/>
    		<geometry>
    			<cylinder radius="0.02" length="0.04"/>
    		</geometry>
    		<material name="blue"/>
    	</collision>
        <inertial>
        	<mass value="0.2"/>
        	<origin xyz="${s_link1_length/2} 0 0" rpy="0 0 0"/>
        	<inertia ixx="0.000054" ixy="0.0" ixz="0.0" iyy="0.000694" iyz="0.0" izz="0.000694"/>
        </inertial>
    </link>

    <joint name="s_joint_1" type="revolute">
        <parent link="s_base_link" />
        <child link="s_link_1" />
        <origin xyz="0.1 0 0.04" rpy="0 0 0"/>
        <axis xyz="0 0 1"/>
        <limit lower="${-degree_135}" upper="${degree_135}" effort="1.5" velocity="6.38791"/>
    </joint>
 
<!--                 link_2 물리량 설정                  -->

    <link name="s_link_2">
        <visual>
        	<origin xyz="${s_link2_length/2} 0 0"/>
        	<geometry>
        		<box size="${s_link2_length} 0.04 0.04"/>
        	</geometry>
        	<material name="green"/>
        </visual>
        <visual> <!-- 둥근 부분 -->
    		<origin xyz="0 0 0"/>
    		<geometry>
    			<cylinder radius="0.02" length="0.04"/>
    		</geometry>
    		<material name="green"/>
    	</visual>
        <visual>
    		<origin xyz="${s_link2_length} 0 0"/>
    		<geometry>
    			<cylinder radius="0.02" length="0.04"/>
    		</geometry>
    		<material name="green"/>
    	</visual>
        <collision>
        	<origin xyz="${s_link2_length/2} 0 0"/>
        	<geometry>
        		<box size="${s_link2_length} 0.04 0.04"/>
        	</geometry>
        </collision>
        <collision> <!-- 둥근 부분 -->
    		<origin xyz="0 0 0.08"/>
    		<geometry>
    			<cylinder radius="0.02" length="0.04"/>
    		</geometry>
    		<material name="green"/>
    	</collision>
        <collision>
    		<origin xyz="${s_link2_length} 0 0"/>
    		<geometry>
    			<cylinder radius="0.02" length="0.04"/>
    		</geometry>
    		<material name="green"/>
    	</collision>
        <inertial>
        	<mass value="0.2"/>
        	<origin xyz="${s_link2_length/2} 0 0" rpy="0 0 0"/>
        	<inertia ixx="0.000054" ixy="0.0" ixz="0.0" iyy="0.000694" iyz="0.0" izz="0.000694"/>
        </inertial>
    </link>
    
    <joint name="s_joint_2" type="revolute">
        <parent link="s_link_1" />
        <child link="s_link_2" />
        <origin xyz="${s_link1_length/2+s_link1_length/2} 0 -0.04" rpy="0 0 0"/>
        <axis xyz="0 0 1"/>
        <limit lower="${-degree_135}" upper="${degree_135}" effort="1.5" velocity="6.38791"/>
    </joint>

    <link name="s_end_effector">
    	
    	<visual>
        	<origin xyz="${s_end_effector_length/2} 0 0"/>
        	<geometry>
        		<box size="${s_end_effector_length} 0.04 0.04"/>
        	</geometry>
        	<material name="red"/>
        </visual>
        <visual> <!-- 둥근 부분 -->
    		<origin xyz="0 0 0"  rpy="1.5708 0 0" />
    		<geometry>
    			<cylinder radius="0.02" length="0.04"/>
    		</geometry>
    		<material name="red"/>
    	</visual>
        <visual>
    		<origin xyz="${s_end_effector_length} 0 0" rpy="0 0 0" />
    		<geometry>
    			<cylinder radius="0.02" length="0.04"/>
    		</geometry>
    		<material name="red"/>
    	</visual>
        <collision>
        	<origin xyz="${s_end_effector_length/2} 0 0"/>
        	<geometry>
        		<box size="${s_end_effector_length} 0.04 0.04" />
        	</geometry>
        </collision>
        <collision> <!-- 둥근 부분 -->
    		<origin xyz="0 0 0" rpy="1.5708 0 0" />
    		<geometry>
    			<cylinder radius="0.02" length="0.04"/>
    		</geometry>
    		<material name="red"/>
    	</collision>
        <collision>
    		<origin xyz="${s_end_effector_length} 0 0" rpy="0 0 0" />
    		<geometry>
    			<cylinder radius="0.02" length="0.04"/>
    		</geometry>
    		<material name="blue"/>
    	</collision>
        <inertial>
        	<mass value="0.2"/>
        	<origin xyz="${s_end_effector_length/2} 0 0" rpy="1.5708 0 0"/>
        	<inertia ixx="0.000054" ixy="0.0" ixz="0.0" iyy="0.000694" iyz="0.0" izz="0.000694"/>
        </inertial>
    </link>

    <joint name="s_end_joint_y" type="revolute">
       	<parent link="s_link_2" />
       	<child link="s_end_effector" />
       	<origin xyz="${s_link2_length} 0 0" rpy="0 0 0"/>
       	<axis xyz="0 1 0"/>
       	<limit lower="${-degree_135}" upper="${degree_135}" effort="1.5" velocity="6.38791"/>
    </joint>

    <joint name="s_end_joint_z" type="revolute">
       	<parent link="s_end_effector" />
       	<child link="s_suction_cup" />
       	<origin xyz="${s_end_effector_length} 0 0" rpy="0 0 0"/>
       	<axis xyz="0 0 1"/>
       	<limit lower="${-degree_135}" upper="${degree_135}" effort="1.5" velocity="6.38791"/>
    </joint>

    <link name="s_suction_cup">
    	<visual>
    		<origin xyz="${s_suction_cup_length/2} 0 0"/>
        	<geometry>
        		<box size="0.02 0.04 0.04"/>
        	</geometry>
        	<material name="blue"/>
        </visual>
       	<visual> <!-- 둥근 부분 -->
   			<origin xyz="0 0 0" rpy="1 0 0"/>
   			<geometry>
   				<cylinder radius="0.02" length="0.04" />
   			</geometry>
   			<material name="blue"/>
   		</visual>
       	<visual>
   			<origin xyz="${s_end_effector_length/2} 0 0" rpy="0 1.5708 0"/>
   			<geometry>
   				<cylinder radius="0.05" length="0.01"/>
   			</geometry>
   			<material name="blue"/>
   		</visual>

       	<collision>
       		<origin xyz="${s_suction_cup_length/2} 0 0"/>
       		<geometry>
       			<box size="0.02 0.04 0.04"/>
       		</geometry>
       	</collision>
       	<collision> <!-- 둥근 부분 -->
   			<origin xyz="0 0 0"/>
    		<geometry>
   				<cylinder radius="0.02" length="0.04"/>
   			</geometry>
   			<material name="blue"/>
   		</collision>
       	<collision>
   			<origin xyz="${s_end_effector_length} 0 0" rpy="0 1.5708 0"/>
   			<geometry>
   				<cylinder radius="0.02" length="0.04"/>
   			</geometry>
   			<material name="blue"/>
   		</collision>

       	<inertial>
       		<mass value="0.2"/>
       		<origin xyz="${s_end_effector_length/2} 0 0" rpy="0 0 0"/>
       		<inertia ixx="0.000054" ixy="0.0" ixz="0.0" iyy="0.000694" iyz="0.0" izz="0.000694"/>
       	</inertial>
    </link>
</robot>



